In [247]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

### Binary classification

In [ ]:
df=pd.read_csv('Datasets/heart.csv')
# sigmooid function is strictly for binary classification 
# if we perform it on mult class then sklearn use softmax or ovr etc under the hood w/o throwing error

In [249]:
df.head(5)

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0

In [250]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [251]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1025 entries, 0 to 1024
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1025 non-null   int64
 1   sex       1025 non-null   int64
 2   cp        1025 non-null   int64
 3   trestbps  1025 non-null   int64
 4   chol      1025 non-null   int64
 5   fbs       1025 non-null   int64
 6   restecg   1025 non-null   int64
 7   thalach   1025 non-null   int64
 8   exang     1025 non-null   int64
 9   oldpeak   1025 non-null   float64
 10  slope     1025 non-null   int64
 11  ca        1025 non-null   int64
 12  thal      1025 non-null   int64
 13  target    1025 non-null   int64
dtypes: float64(1), int64(13)
memory usage: 112.2 KB

In [252]:
df.describe()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
count,1025.000000,1025.000000,1025.000000,1025.000000,1025.00000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000,1025.000000
mean,54.434146,0.695610,0.942439,131.611707,246.00000,0.149268,0.529756,149.114146,0.336585,1.071512,1.385366,0.754146,2.323902,0.513171
std,9.072290,0.460373,1.029641,17.516718,51.59251,0.356527,0.527878,23.005724,0.472772,1.175053,0.617755,1.030798,0.620660,0.500070
min,29.000000,0.000000,0.000000,94.000000,126.00000,0.000000,0.000000,71.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,48.000000,0.000000,0.000000,120.000000,211.00000,0.000000,0.000000,132.000000,0.000000,0.000000,1.000000,0.000000,2.000000,0.000000
50%,56.000000,1.000000,1.000000,130.000000,240.00000,0.000000,1.000000,152.000000,0.000000,0.800000,1.000000,0.000000,2.000000,1.000000
75%,61.000000,1.000000,2.000000,140.000000,275.00000,0.000000,1.000000,166.000000,1.000000,1.800000,2.000000,1.000000,3.000000,1.000000
max,77.000000,1.000000,3.000000,200.000000,564.00000,1.000000,2.000000,202.000000,1.000000,6.200000,2.000000,4.000000,3.000000,1.000000

In [253]:
df.corr()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
age,1.000000,-0.103240,-0.071966,0.271121,0.219823,0.121243,-0.132696,-0.390227,0.088163,0.208137,-0.169105,0.271551,0.072297,-0.229324
sex,-0.103240,1.000000,-0.041119,-0.078974,-0.198258,0.027200,-0.055117,-0.049365,0.139157,0.084687,-0.026666,0.111729,0.198424,-0.279501
cp,-0.071966,-0.041119,1.000000,0.038177,-0.081641,0.079294,0.043581,0.306839,-0.401513,-0.174733,0.131633,-0.176206,-0.163341,0.434854
trestbps,0.271121,-0.078974,0.038177,1.000000,0.127977,0.181767,-0.123794,-0.039264,0.061197,0.187434,-0.120445,0.104554,0.059276,-0.138772
chol,0.219823,-0.198258,-0.081641,0.127977,1.000000,0.026917,-0.147410,-0.021772,0.067382,0.064880,-0.014248,0.074259,0.100244,-0.099966
fbs,0.121243,0.027200,0.079294,0.181767,0.026917,1.000000,-0.104051,-0.008866,0.049261,0.010859,-0.061902,0.137156,-0.042177,-0.041164
restecg,-0.132696,-0.055117,0.043581,-0.123794,-0.147410,-0.104051,1.000000,0.048411,-0.065606,-0.050114,0.086086,-0.078072,-0.020504,0.134468
thalach,-0.390227,-0.049365,0.306839,-0.039264,-0.021772,-0.008866,0.048411,1.000000,-0.380281,-0.349796,0.395308,-0.207888,-0.098068,0.422895
exang,0.088163,0.139157,-0.401513,0.061197,0.067382,0.049261,-0.065606,-0.380281,1.000000,0.310844,-0.267335,0.107849,0.197201,-0.438029
oldpeak,0.208137,0.084687,-0.174733,0.187434,0.064880,0.010859,-0.050114,-0.349796,0.310844,1.000000,-0.575189,0.221816,0.202672,-0.438441
slope,-0.169105,-0.026666,0.131633,-0.120445,-0.014248,-0.061902,0.086086,0.395308,-0.267335,-0.575189,1.000000,-0.073440,-0.094090,0.345512
ca,0.271551,0.111729,-0.176206,0.104554,0.074259,0.137156,-0.078072,-0.207888,0.107849,0.221816,-0.073440,1.000000,0.149014,-0.382085
thal,0.072297,0.198424,-0.163341,0.059276,0.100244,-0.042177,-0.020504,-0.098068,0.197201,0.202672,-0.094090,0.149014,1.000000,-0.337838
target,-0.229324,-0.279501,0.434854,-0.138772,-0.099966,-0.041164,0.134468,0.422895,-0.438029,-0.438441,0.345512,-0.382085,-0.337838,1.000000

In [254]:
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [255]:
df.duplicated().sum()

np.int64(723)

In [256]:
df=df.drop_duplicates()
df.drop_duplicates(inplace=True)

In [257]:
df.duplicated().sum()

np.int64(0)

In [258]:
df.shape

(302, 14)

In [259]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

In [260]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [261]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [262]:
lor=LogisticRegression(max_iter=100)
lor.fit(X_train,y_train)

c:\Users\yashi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [263]:
pred=lor.predict(X_test)

In [264]:
print(precision_score(y_test,pred))
print(recall_score(y_test,pred))
print(precision_score(y_test,pred,average=None))
print(recall_score(y_test,pred,average=None))

0.8
0.9333333333333333
[0.92307692 0.8       ]
[0.77419355 0.93333333]

In [265]:
confusion_matrix(y_test,pred)

array([[24,  7],
       [ 2, 28]])

In [266]:
accuracy_score(y_test,pred)

0.8524590163934426

In [267]:
tree=DecisionTreeClassifier(max_depth=2)
tree.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2)

In [268]:
y_pred=tree.predict(X_test)

In [269]:
confusion_matrix(y_test,y_pred)

array([[24,  7],
       [ 7, 23]])

In [270]:
accuracy_score(y_test,y_pred)

0.7704918032786885

In [271]:
print(precision_score(y_test,y_pred))
print(recall_score(y_test,y_pred))
print(precision_score(y_test,y_pred,average=None))
print(recall_score(y_test,y_pred,average=None))

0.7666666666666667
0.7666666666666667
[0.77419355 0.76666667]
[0.77419355 0.76666667]

### Multi-class classification

In [280]:
df=pd.read_csv("Datasets/iris.csv")

In [281]:
df.head(5)

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [282]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
df['Species'] = encoder.fit_transform(df['Species'])

In [283]:
df.sample(5)

      Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
139  140            6.9           3.1            5.4           2.1        2
44    45            5.1           3.8            1.9           0.4        0
10    11            5.4           3.7            1.5           0.2        0
66    67            5.6           3.0            4.5           1.5        1
68    69            6.2           2.2            4.5           1.5        1

In [284]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=1)

In [285]:

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [286]:

clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [287]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

c:\Users\yashi\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [288]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [292]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score

In [289]:
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 1.0
Accuracy of Decision Trees 0.9666666666666667

In [ ]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,3)))

Logistic Regression Confusion Matrix

    0   1  2
0  11   0  0
1   0  13  0
2   0   0  6

In [291]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,3)))

Decision Tree Confusion Matrix

    0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

In [298]:
print("Logistic precision : ",precision_score(y_test,y_pred1,average='macro'))
print("Logistic recall : ",recall_score(y_test,y_pred1,average='macro'))
print("Decision precision : ",precision_score(y_test,y_pred2,average='macro'))
print("Decision recall : ",recall_score(y_test,y_pred2,average='macro'))

Logistic precision :  1.0
Logistic recall :  1.0
Decision precision :  0.9523809523809524
Decision recall :  0.9743589743589745

In [299]:
print("Classes learned:", clf1.classes_)
print("Coefficients shape:", clf1.coef_.shape)
print("Intercepts shape:", clf1.intercept_.shape)

Classes learned: [0 1 2]
Coefficients shape: (3, 5)
Intercepts shape: (3,)